#!/bin/sh
# vim:set ft=sh et sw=4 sts=4:

alias cd..='cd ..'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'

alias dirf='find . -type d | sed -e "s/[^-][^\/]*\//  |/g" -e "s/|\([^ ]\)/|-\1/"'
alias irc="screen -rdU irc"
alias urg="mutt -Rf /home/stu/Mail/urgmatch"
alias dim="mutt -Rf /home/stu/Mail/dimins"
alias mim="mutt -Rf /home/stu/Mail/mfolder"
alias grep="grep --color=auto"
alias free="free -m"
alias sls="screen -ls"
alias srd="screen -rd"
alias lynx="lynx -accept_all_cookies"
alias cdcgi="cd ~/public_html/cgi-bin/"
# listing aliases # git://github.com/davidmiller/mydotfiles.git
alias ls="ls --color=auto"
alias ll='ls -hlrt'

alias lx='ls -lXB'             # sort by extension
alias lk='ls -lSr'             # sort by size
alias lsa='ls -lah'            # list including .dotfiles
alias lsf='ls -lh | grep "^-"'
alias lsd='ls -lh | grep "^d"' # list only directories
alias lsl='ls -lh | grep "^l"' # list only links

# vim:filetype=sh
