#!/bin/sh
# vim:set ft=sh et sw=4 sts=4:

function jail_add_path() {

if [[ -d /di/solution/executables ]]; then
   if ! [[ :$PATH: = *:/di/solution/executables:* ]]; then
		PATH=$PATH:/di/solution/executables
		return
   fi
fi

if [[ -d /di/atlantis/executables ]]; then
   if ! [[ :$PATH: = *:/di/atlantis/executables:* ]]; then
		PATH=$PATH:/di/atlantis/executables
		return
   fi
fi

if [[ -d /di_solution/executables ]]; then
   if ! [[ :$PATH: = *:/di_solution/executables:* ]]; then
		PATH=$PATH:/di_solution/executables
		return
   fi
fi

if [[ -d /di_atlantis/executables ]]; then
   if ! [[ :$PATH: = *:/di_atlantis/executables:* ]]; then
		PATH=$PATH:/di_atlantis/executables
		return
   fi
fi

}

jail_add_path

function _cmd_logs()
{
	local ldirs=()

	if [ -d /di/logs/commands/ ];  then
		ldirs+=("/di/logs/commands/")	
	fi

	if [ -d /di/logs/archives/ ];  then
		ldirs+=("/di/logs/archives/")	
	fi

	echo ${ldirs[*]}

	awk '{print $4, $5}' /di/logs/commands/integ_all_commands.log


}

[ -d /di_atlantis/dl-dataroot/ ] && export DATAROOT=/di_atlantis/dl-dataroot
[ -d /di/solution/dl-dataroot/ ] && export DATAROOT=/di/solution/dl-dataroot


function oldmodels()
{
    find -L "$@" -mtime +10 -name "*.md*" -exec ls -lt {} +
}

function model_dirs()
{
    TIME={$1-10}
    find -L $DATAROOT/data/ -name "*.md*" -type f -exec dirname {} \; | sort -u

    find -L $DATAROOT/data/ -name "*.md*" -type f -exec dirname {} \; | sort -u |
        while read line; do
            find $line -maxdepth 1 -type f -mtime +${TIME} -name "*.md*" -exec \
            stat --printf "%b\t%n\t%y\n" {} +;
        done
}

function dir_size_time()
{
    echo foo
}

function script_logs ()
{

	FILE=$1
	[[ -f $FILE ]] || exit 1

}

